# Site settings
title: Puzzo on Software
email: chris.puzzo@gmail.com
description: A place to write things about other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://puzzfuzz.github.io/" # the base hostname & protocol for your site
twitter_username: @cpuzzo
github_username:  puzzfuzz
highlighter: pygments

# Build settings
markdown: kramdown

