# Site settings
title: ChrisP Software - Adding Texture to Every Byte
email: chris.puzzo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to write things about other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  puzzfuzz
highlighter: pygments

# Build settings
markdown: kramdown

